# Generated by Django 4.1.7 on 2023-03-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(help_text='Введите имя', max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(help_text='Введите отчество', max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(help_text='Выберите регион вашего проживания', max_length=255, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(help_text='Введите фамилию', max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='town',
            field=models.CharField(help_text='Введите название вашего населенного пункта', max_length=255, verbose_name='Населенный пункт'),
        ),
    ]
