# Generated by Django 4.1.7 on 2023-03-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_name_alter_customuser_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Учителя', 'verbose_name_plural': 'Учителя'},
        ),
    ]
