# Generated by Django 4.1.7 on 2023-02-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название теста', max_length=255, verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Введите вопрос', max_length=255, verbose_name='Вопрос')),
                ('test', models.ForeignKey(help_text='Выберите тест, к которому относится вопрос', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.tests', verbose_name='Тест')),
            ],
        ),
    ]
