# Generated by Django 4.1.7 on 2023-02-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varAnswer', models.CharField(help_text='Введите вариант ответа', max_length=255, verbose_name='Вариант ответа')),
                ('correctAnswer', models.BooleanField(help_text='Этот ответ правильный?', verbose_name='Ответ правильный?')),
                ('question', models.ForeignKey(help_text='Выберите вопрос, к которому относится этот вариант ответа', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.questions', verbose_name='Вопрос')),
            ],
        ),
    ]
