# Generated by Django 4.1.7 on 2023-02-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_answersvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agedef', models.CharField(help_text='Введите возрастную группу', max_length=255, verbose_name='Возрастная группа')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название цикла тестов', max_length=255, verbose_name='Цикл тестов')),
            ],
        ),
        migrations.RemoveField(
            model_name='tests',
            name='name',
        ),
        migrations.AddField(
            model_name='tests',
            name='agedef',
            field=models.ForeignKey(help_text='Выберите возрастную группу для теста', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.testage', verbose_name='Возрастная группа'),
        ),
        migrations.AddField(
            model_name='tests',
            name='themetest',
            field=models.ForeignKey(help_text='Выберите тематику теста', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.themetest', verbose_name='Тематика теста'),
        ),
    ]
