# Generated by Django 4.1.7 on 2023-02-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_testage_options_alter_tests_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersvariant',
            options={'verbose_name': 'Варианты ответов', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='testage',
            options={'ordering': ['agedef'], 'verbose_name': 'Возрастные группы', 'verbose_name_plural': 'Возрастные группы'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ['agedef'], 'verbose_name': 'Тесты', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='themetest',
            options={'ordering': ['name'], 'verbose_name': 'Тематика тестов', 'verbose_name_plural': 'Тематика тестов'},
        ),
    ]
