# Generated by Django 4.1.7 on 2023-02-22 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0005_alter_answersvariant_options_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Введите фамилию ученика', max_length=255, verbose_name='Фамилия ученика')),
                ('name', models.CharField(help_text='Введите имя ученика', max_length=255, verbose_name='Имя ученика')),
                ('answerstud', models.CharField(max_length=255, verbose_name='Ответ ученика')),
                ('question', models.ForeignKey(help_text='Выберите вопрос, к которому относится этот ответ', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.questions', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Ответы учеников',
                'verbose_name_plural': 'Ответы учеников',
            },
        ),
    ]
