# Generated by Django 4.1.7 on 2023-02-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_answerstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='themetest',
            name='fromdate',
            field=models.DateField(blank=True, help_text='Введите дату начала теста', null=True, verbose_name='Дата начала теста'),
        ),
        migrations.AddField(
            model_name='themetest',
            name='tilldate',
            field=models.DateField(blank=True, help_text='Введите дату окончания теста', null=True, verbose_name='Дата окончания теста'),
        ),
    ]
