# Generated by Django 4.1.7 on 2023-03-03 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0007_themetest_fromdate_themetest_tilldate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themetest',
            options={'ordering': ['fromdate'], 'verbose_name': 'Тематика тестов', 'verbose_name_plural': 'Тематика тестов'},
        ),
        migrations.RemoveField(
            model_name='answerstudent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='answerstudent',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='answerstudent',
            name='user',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Введите фамилию ученика', max_length=255, verbose_name='Фамилия ученика')),
                ('name', models.CharField(help_text='Введите имя ученика', max_length=255, verbose_name='Имя ученика')),
                ('town', models.CharField(help_text='Введите название населенного пункта', max_length=255, verbose_name='Населенный пункт')),
                ('school', models.CharField(help_text='Введите название образовательного учреждения', max_length=255, verbose_name='Образовательное учреждение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
        ),
        migrations.AddField(
            model_name='answerstudent',
            name='student',
            field=models.ForeignKey(help_text='Выберите ученика', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.student', verbose_name='Ученик'),
        ),
    ]
