# Generated by Django 4.1.7 on 2023-03-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_remove_answerstudent_student_remove_results_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerStudent',
        ),
    ]
