# Generated by Django 4.1.7 on 2023-03-09 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0016_alter_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.AddField(
            model_name='tests',
            name='userpay',
            field=models.ManyToManyField(help_text='Выберите покупателей', null=True, to='tests.userpay', verbose_name='Покупатели'),
        ),
    ]
