# Generated by Django 4.1.7 on 2023-03-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_alter_tests_userpay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPay',
        ),
    ]
