# Generated by Django 4.1.7 on 2023-03-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_delete_userpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ForeignKey(help_text='Выберите тест, в котором будет участвовать ученик', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.tests', verbose_name='Тест'),
        ),
    ]
