# Generated by Django 4.1.7 on 2023-03-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_student_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='userpay',
        ),
    ]
